model_list:
  - model_name: deepseek-chat
    litellm_params:
      model: gemini/gemini-1.5-flash
      api_key: env/GEMINI_API_KEY

  - model_name: deepseek-r1
    litellm_params:
      model: gemini/gemini-1.5-pro
      api_key: env/GEMINI_API_KEY
